[package]
name = "mabi-knx"
description = "Mabinogion - KNXnet/IP simulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/mabi-knx"
readme = "README.md"
keywords = ["knx", "protocol", "simulator", "home-automation", "building"]
categories = ["simulation", "network-programming"]

[dependencies]
mabi-core = { version = "1.1.7", path = "../mabi-core" }

tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
bytes = { workspace = true }
socket2 = { workspace = true }
lazy_static = "1.4"
chrono = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
