use super::{
    GeneratedNodeCatalog, GeneratedRustModule, GeneratedTypeCatalog, GeneratedTypeEntry,
    GeneratedTypesConfig,
};

pub(crate) fn build_generated_type_catalog(
    session_name: &str,
    catalog: &GeneratedNodeCatalog,
    config: &GeneratedTypesConfig,
    service_name: Option<&str>,
) -> GeneratedTypeCatalog {
    let module_name = config
        .module_name
        .clone()
        .unwrap_or_else(|| sanitize_rust_ident(service_name.unwrap_or(session_name)));
    let mut entries = Vec::new();
    for node in &catalog.nodes {
        entries.push(GeneratedTypeEntry {
            rust_ident: sanitize_rust_ident(&node.browse_name().name),
            node_id: node.node_id().to_string(),
            browse_name: node.browse_name().name.clone(),
            display_name: node.display_name().text.clone(),
            node_class: node.node_class_name().into(),
        });
    }
    entries.sort_by(|left, right| left.rust_ident.cmp(&right.rust_ident));

    GeneratedTypeCatalog {
        session_name: session_name.to_string(),
        module_name,
        entries,
    }
}

pub(crate) fn render_generated_rust_module(catalog: &GeneratedTypeCatalog) -> GeneratedRustModule {
    let mut source = String::new();
    source.push_str("// Generated by mabi-opcua::generate_types\n");
    source.push_str("use mabi_opcua::NodeId;\n\n");
    source.push_str(&format!("pub mod {} {{\n", catalog.module_name));
    source.push_str("    use super::NodeId;\n\n");
    for entry in &catalog.entries {
        source.push_str(&format!(
            "    pub fn {}() -> NodeId {{ \"{}\".parse().expect(\"generated node id\") }}\n",
            entry.rust_ident, entry.node_id
        ));
    }
    source.push_str("}\n");

    let manifest_json = serde_json::to_string_pretty(catalog).unwrap_or_else(|_| "{}".into());
    GeneratedRustModule {
        module_name: catalog.module_name.clone(),
        source,
        manifest_json,
    }
}

fn sanitize_rust_ident(value: &str) -> String {
    let mut ident = String::with_capacity(value.len());
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            ident.push(ch.to_ascii_lowercase());
        } else {
            ident.push('_');
        }
    }
    let ident = ident.trim_matches('_');
    let ident = if ident.is_empty() {
        "generated_node"
    } else {
        ident
    };
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("node_{}", ident)
    } else {
        ident.to_string()
    }
}
